# Generated by Django 3.2.8 on 2021-11-07 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20211102_2206'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PromoProgram',
        ),
    ]
