# Generated by Django 3.2.8 on 2021-11-07 17:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_delete_promoprogram'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromoProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registered', models.BooleanField()),
                ('penjual_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.penjual')),
            ],
        ),
    ]
