# Generated by Django 3.2.8 on 2021-11-07 18:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20211108_0146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promo',
            name='penjual_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.penjual'),
        ),
    ]
