# Generated by Django 3.2.8 on 2021-11-07 18:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_promo_penjual_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promo',
            name='penjual_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promo', to='api.penjual'),
        ),
    ]
